### ISSUE TITLE
missing some files

### ISSUE THREAD

**Issue by w136111526** [ltjax/image-packer#1]
Hi, I downloaded your code, but it's missing a lot of files.  example:
#include <replay/pixbuf.hpp>
#include <replay/pixbuf_io.hpp>
#include <replay/box_packer.hpp>
#include <replay/vector2.hpp>

**Comment by ltjax** [comment]
Hello! They are included as a git submodule - not the most convenient choice, I know. Sorry about that. If you clone the repo with `git clone --recurse-submodules https://github.com/ltjax/image-packer.git`, you should get them. Alternatively, you can get them here: https://github.com/ltjax/replay

**Comment by w136111526** [comment]
Hello, I would like to set up a normal PNG image, set up a specific location to generate the 9 pictures used by Android, I would like to ask you if your code can be implemented

**Comment by ltjax** [comment]
I'm not entirely sure what you are asking. Do you want to generate images for android?

**Comment by w136111526** [comment]
Yes, I 'd like to make a 9 patch image generator.

**Comment by ltjax** [comment]
Well, this project is not meant to be used with Android. It just takes the ideas of the 9patch format, e.g. the black bars, and puts them in a metadata file so you can read that with your "engine", which is a custom UI library for me. Splitting the image into 9 actual distinct images sounds like a very bad idea, performance wise.

**Comment by w136111526** [comment]
Do you mean that I can load an image and save it in 9 patch format

**Comment by ltjax** [comment]
No, this takes images already in 9-patch format and extracts that information.

**Comment by w136111526** [comment]
I want to reverse the operation, how to do I , can you achieve It?

**Comment by ltjax** [comment]
Any paint program can do it. You just have to draw those black lines.
